adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.01
batch_size: 4
checkpointing_steps: 1000
datapath: /media/zliu/data12/dataset/Sintel/
datathread: 4
gradient_accumulation_steps: 1
learning_rate: 0.0001
local_rank: -1
logging_dir: /home/zliu/Desktop/NIPS2024/UnsupervisedStereo/StereoSDF/stereonet_logs
loss_type: simple
lr_scheduler: cosine
lr_warmup_steps: 500
max_grad_norm: 1.0
max_train_steps: 20000
maxdisp: 192
mixed_precision: null
network_type: StereoNet
num_train_epochs: 84
output_dir: /home/zliu/Desktop/NIPS2024/UnsupervisedStereo/StereoSDF/outputs/simple_stereonet
prediction_type: null
report_to: tensorboard
resume_from_checkpoint: null
scale_lr: false
seed: 10086
tracker_project_name: tracker_project_MPI
trainlist: /home/zliu/Desktop/NIPS2024/UnsupervisedStereo/StereoSDF/filenames/MPI/MPI_Train_Sub_List.txt
use_8bit_adam: false
vallist: /home/zliu/Desktop/NIPS2024/UnsupervisedStereo/StereoSDF/filenames/MPI/MPI_Val_Sub_List.txt
visible_list: '[''final_left'',''final_right'',''disp'',''occlusions'',''outofframe'']'
