adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.01
batch_size: 2
center_view_datapath: /data1/KITTI/Rendered_Results/Simple_UNet/KITTI_Train_SmallSet/
checkpointing_steps: 100
confidence_datapath: /data1/KITTI/Rendered_Results/Simple_UNet/Reference_PSNR/
datathread: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-05
local_rank: 0
logging_dir: /home/zliu/Desktop/UnsupervisedStereo/StereoSDF/logs_outside_test
loss_type: plusoutside
lr_scheduler: cosine
lr_warmup_steps: 500
max_grad_norm: 1.0
max_train_steps: 15000
maxdisp: 192
mixed_precision: null
num_train_epochs: 36
output_dir: /home/zliu/Desktop/UnsupervisedStereo/StereoSDF/outputs/outside_pamstereo_test
outside_view_datapath: /data1/KITTI/Rendered_Results/Simple_UNet/KITTI_Train
prediction_type: null
report_to: tensorboard
resume_from_checkpoint: null
scale_lr: false
seed: 10086
source_datapath: /data1/KITTI/KITTI_Raw/
tracker_project_name: tracker_project_kitti_raw_plus_outside2
trainlist: /home/zliu/Desktop/UnsupervisedStereo/StereoSDF/filenames/KITTISmallSet/new_kitti_raw_subset2.txt
use_8bit_adam: false
vallist: /home/zliu/Desktop/UnsupervisedStereo/StereoSDF/filenames/KITTI_2015_train.txt
visible_list: '[''left'',''right'',''left_left'',''right_right'']'
